# Generated by Django 5.2.13 on 2026-04-24 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_seed_sections'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking_per_student_session',
        ),
        migrations.AddField(
            model_name='user',
            name='primary_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_students', to='scheduling.section'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('session', 'student'), name='unique_active_booking_per_student_session'),
        ),
    ]
