# Generated by Django 5.2.13 on 2026-04-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_remove_booking_unique_booking_per_student_session_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recoverycredit',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'holiday_closure')), fields=('student', 'origin_session', 'source'), name='unique_holiday_closure_credit_per_student_session'),
        ),
    ]
