# Generated by Django 5.2.13 on 2026-05-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_recoverycredit_unique_holiday_closure_credit_per_student_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='moved_from_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_to_booking', to='scheduling.booking'),
        ),
    ]
