# Generated by Django 5.2.13 on 2026-06-22 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_booking_moved_from_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_monthly_plans', to='scheduling.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', 'student__last_name', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentMonthlyPlanSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('monthly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_slots', to='scheduling.studentmonthlyplan')),
                ('weekly_class_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_monthly_plan_slots', to='scheduling.weeklyclassslot')),
            ],
            options={
                'ordering': ['position', 'weekly_class_slot__weekday', 'weekly_class_slot__start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='studentmonthlyplan',
            constraint=models.UniqueConstraint(fields=('student', 'month'), name='unique_student_monthly_plan_per_month'),
        ),
        migrations.AddConstraint(
            model_name='studentmonthlyplanslot',
            constraint=models.UniqueConstraint(fields=('monthly_plan', 'weekly_class_slot'), name='unique_student_monthly_plan_slot'),
        ),
        migrations.AddConstraint(
            model_name='studentmonthlyplanslot',
            constraint=models.UniqueConstraint(fields=('monthly_plan', 'position'), name='unique_student_monthly_plan_slot_position'),
        ),
    ]
