# Generated by Django 5.2.15 on 2026-06-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_studentmonthlyplan_multi_section_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycredit',
            name='source',
            field=models.CharField(choices=[('timely_cancellation', 'Timely Cancellation'), ('holiday_closure', 'Holiday Closure'), ('session_cancellation', 'Session Cancellation'), ('manual', 'Manual')], max_length=30),
        ),
    ]
