# Generated by Django 5.2.15 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_alter_recoverycredit_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(
                blank=True,
                choices=[('global_deactivation', 'Global Deactivation')],
                max_length=32,
                null=True,
            ),
        ),
    ]
