# Generated by Django 5.2.15 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_booking_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_plan_reset_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
