databases:
  - name: eunoia-db
    plan: basic-256mb

services:
  - type: web
    name: eunoia
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn config.wsgi --log-file -
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_USE_SQLITE
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: eunoia-db
          property: connectionString
      - key: DJANGO_DB_SSL_MODE
        value: require
      - key: DJANGO_DB_CONNECT_TIMEOUT
        value: "5"
      - key: DJANGO_DB_CONN_MAX_AGE
        value: "60"
      - key: DJANGO_SECURE_SSL_REDIRECT
        value: "True"
      - key: EUNOIA_DEFAULT_TEMPORARY_PASSWORD
        sync: false
      - key: EUNOIA_ADMIN_EMAIL
        sync: false
      - key: EUNOIA_ADMIN_PASSWORD
        sync: false
